# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: check-added-large-files
    -   id: check-toml
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace

-   repo: https://github.com/pycqa/flake8
    rev: '3.9.2'
    hooks:
    -   id: flake8
        args: ['--max-line-length', "90"]

-   repo: https://github.com/timothycrosley/isort
    rev: 5.7.0
    hooks:
    -   id: isort
        additional_dependencies: [toml]
        exclude: ^.*/?setup\.py$
        args: ['--profile', "black"]

-   repo: https://github.com/psf/black
    rev: 21.6b0
    hooks:
    -   id: black
        args: ['--line-length', "90"]

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.902
    hooks:
    -   id: mypy
        args: ["--ignore-missing-imports", "--scripts-are-modules"]

-   repo: https://github.com/returntocorp/semgrep
    rev: v0.56.0
    hooks:
    -   id: semgrep
        name: Semgrep Python
        types: [python]
        exclude: "^semgrep/tests/.+$|^scripts/.+$|^semgrep/setup.py$"
        args: ['--config', 'https://semgrep.dev/p/python', '--error']
